AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: favorites-service

Globals:
  Function:
    Tracing: Active

Resources:
  AddFavoriteLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: java11
      MemorySize: 3008
      Handler: com.drissamri.favorites.AddFavoriteLambda::handle
      CodeUri: target/lambda.zip
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref FavoritesTable
      Events:
        list:
          Type: HttpApi
          Properties:
            Path: /favorites
            Method: POST
            PayloadFormatVersion: "2.0"
      Environment:
        Variables:
          TABLE_NAME: !Ref FavoritesTable
          REGION: eu-central-1

  FavoritesTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: id
        Type: String

Outputs:
  AddFavoriteApiEndpoint:
    Description: "HTTP API endpoint URL"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/favorites"

# TODO: Log Retention
# TODO: S3 Retention